### ISSUE TITLE
Batarangle doesn't render component tree as expected

### ISSUE THREAD

**Issue by sumitarora** [rangle/batarangle#172]
- Component tree is not getting rendered for scenario http://plnkr.co/edit/?p=preview 
-  `Uncaught TypeError: Cannot read property 'componentType' of null` error in console might be the root cause

**Comment by mko** [comment]
+1

**Comment by mko** [comment]
It should be noted that I don't get the `Uncaught TypeError` in my app where this occurs.

Here's my original bug report:

When I inspect using Batarangle, I currently only see Components that are defined outside of the `router-outlet` (i.e. in the core app component tree without being implemented as a routed view. Is that the expected behavior, or is there potentially something I’ve done in how I configured my router that is blocking Batarangle from access? I can’t reproduce the issue in a Plunker like I expected, but I’m basically just set up like https://angular.io/docs/ts/latest/guide/router.html is. In the Component Inspector, I can find the component (the host component of the routed view) and can start following it down and inspecting it, but in the Angular2 tab of the DevTools, it doesn’t show up.
