### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by johnpapa** [rangle/batarangle#59]
Went through the instructions but now getting this error:

![image](https://cloud.githubusercontent.com/assets/1202528/10923149/272a58f4-8234-11e5-8abf-192e669f168f.png)

**Comment by igor-ka** [comment]
@johnpapa it looks like the extension does not get built. Judging by the error no "build" folder was generated (it should be generated in the root of the project).

Reading through our instructions, i see that it should say ```npm run build``` in step 3, instead of ```npm build```. 

Can you try ```npm run build``` instead? I'll update our readme if that helps.

**Comment by johnpapa** [comment]
i  did `rm -rf node_modules` and then `npm install && npm build` and it worked
