### ISSUE TITLE
message: "ng is not defined"

### ISSUE THREAD

**Issue by asadsahi** [rangle/batarangle#71]
I am trying to use batarangle with this repo:

https://github.com/robianmcd/ng2-movies

But having above message in the components panel. Also, nothing shows in angular 2 panel in developers tools.

**Comment by igor-ka** [comment]
@asadsahi the issue is that you have to make a slight modification to your application to get it working with Batarangle. Refer to our example todo-mvc app (here)[https://github.com/rangle/batarangle/blob/master/example-apps/todo-mvc-example/source/app.ts]

We will update our documentation shortly to reflect this. Once we are ready to release this will not have to be done.

Let me know how that works out for you or if you have any more issues. Otherwise thank you for your feedback!

**Comment by bertrandk** [comment]
Like @igor-ka said, we're working on improving the documentation in this case[1].

For this current release, you'll want to bind the default `AppViewListener` to `DebugElementViewListener` [2] during bootstrapping.

In your app, it should look something like this once you're imported the two modules [3]:
```
bootstrap(App, [
  bind(AppViewListener).toClass(DebugElementViewListener)
  ROUTER_PROVIDERS,
  HTTP_PROVIDERS,
  MovieApi
]);
```

The process exposes an `ng` global object. Hope that helps.

[1] #67 
[2] https://github.com/rangle/batarangle/blob/4d2e33b7ddaa3bdcb7bbf68b04f10e7f2085d4cf/example-apps/todo-mvc-example/source/app.ts#L10
[3] see https://github.com/rangle/batarangle/blob/4d2e33b7ddaa3bdcb7bbf68b04f10e7f2085d4cf/example-apps/todo-mvc-example/source/app.ts#L5 and https://github.com/rangle/batarangle/blob/4d2e33b7ddaa3bdcb7bbf68b04f10e7f2085d4cf/example-apps/todo-mvc-example/source/app.ts#L6

**Comment by asadsahi** [comment]
Thanks Guys :+1:
